### PR TITLE
Issue 53 unittest flask web app

### LINKED ISSUE #53: unittest flask web app
# setup unittest flask web app

## test_init.py
- app is created
- app config is as expected in config.py

## test_route.py
- app render the right template
- app handle request as expected
- app handle .docx file as expected 
- app extract rsid and metadata as expected
- app handle error as expected

## test_forms.py
- app validate user input, .docx files in this case
- app handle invalid input as expected

### PR DESCRIPTION
**Pull request by Lu0922**
# unittest for flask app

test for GET and POST method

GET: 
assert get correct response
assert status code is correct
assert the content of response are as expected

POST:
send request without uploading file
send request without correct file
send request with over limit file

#53

# Related issue

- Resolve #53

### CODE REVIEW

**Comment by Elijah017** [comment]
I'm wondering whether there is a way to do the testing on the actual files that we are running? I recall in Agile Web there was something about being able to switch configs and do some stuff depending on whether we wanted to run in debug or test or whatnot. Are we able to do that for this, because it seems somewhat excessive and error prone cloning the project files into the test directory and doing the tests that way.

**Comment by loklokyx** [comment]
Agile Web unit taught the way similar to this.
```
import unittest
from app import create_app
from config import TestingConfig

unittest.TestLoader.sortTestMethodsUsing = None

class BaseTestCase(unittest.TestCase):
    def setUp(self):
        testApp = create_app(TestingConfig)
        self.app_context = testApp.app_context()
        self.app_context.push()

    def tearDown(self):
        self.app_context.pop()

# test case here ...

if __name__ == '__main__':
    unittest.main(verbosity=1)
```

**Comment by Lu0922** [comment]
We can do this by exporting FLASK_CONFIG manually, but doing this we need to import pytest and possibly some other modules to the app which may not be useful to the client. For now the test is just calling the functions in  /app to make sure the codes are doing as expected. Maybe we can integrate the test to the actual app on the next step?

**Comment by Elijah017** [comment]
Are the tests able to built in their own files and we simply don't include those files whenever we are running/deploying the app, they're only used during the testing pipeline?

**Comment by Lu0922** [comment]
yes, the test will generate .docx files if there is none placing in /test/testdocs. For now, we do not need to include anything in /test when running the app. 

The /test folder needs to place in the same directory to run the test, but /app do not require anything in /test. which means we can discard /test if we do not want it in deploy

**Review by Elijah017 — APPROVED** [review]

**Review by normit581 — APPROVED** [review]

**Review by loklokyx — APPROVED** [review]
setup and test case looks good. Can merge anytime when u ready,

**Pull request merged**
